title: Mirae Research Portfolio
description: Temple Food, Health, and Public Health
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
collections:
  journal:
    output: true
    permalink: /journal/:name/
  interviews:
    output: true
    permalink: /interviews/:name/
  sources:
    output: true
    permalink: /sources/:name/
  reflections:
    output: true
    permalink: /final-reflection/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: journal
    values:
      layout: entry
      category_label: Journal
  - scope:
      path: ""
      type: interviews
    values:
      layout: entry
      category_label: Interviews
  - scope:
      path: ""
      type: sources
    values:
      layout: entry
      category_label: Sources & Notes
  - scope:
      path: ""
      type: reflections
    values:
      layout: entry
      category_label: Final Reflection
