backend:
  name: github
  repo: miraechung0126/researchportfolio
  branch: main

site_url: https://miraechung0126.github.io/researchportfolio/
display_url: https://miraechung0126.github.io/researchportfolio/
logo_url: /researchportfolio/assets/images/lotus.png
publish_mode: simple
media_folder: assets/uploads
public_folder: /researchportfolio/assets/uploads

collections:
  - name: journal
    label: Journal
    folder: _journal
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown

  - name: interviews
    label: Interviews
    folder: _interviews
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown

  - name: sources
    label: Sources & Notes
    folder: _sources
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown

  - name: reflections
    label: Final Reflection
    folder: _reflections
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
